#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Environment;
use Yiisoft\Yii\Runner\Console\ConsoleApplicationRunner;

require_once __DIR__ . '/vendor/autoload.php';

$env = new App\Environment();
$env->loadFromFile(__DIR__ . '/.env');

// Run console application runner
$runner = new ConsoleApplicationRunner(
    rootPath: __DIR__,
    debug: $env->get('APP_DEBUG'),
    checkEvents: $env->get('APP_DEBUG'),
    environment: $env->get('APP_ENV'),
);
$runner->run();
